### PR TITLE
Release 1.0.0

### PR DESCRIPTION
**Pull request by tas50**
### Description

[Describe what this change achieves]

### Issues Resolved

[List any existing issues this PR resolves]

### Check List
- [ ] All tests pass. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] The CLA has been signed. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD

### CODE REVIEW

**Comment by tas50** [comment]
@schisamo @yzl Thoughts on merging / releasing 1.0.0.  There's a FC failure, but I can disable that rule later. It was failing already.

**Comment by yzl** [comment]
cc @scotthain

**Comment by scotthain** [comment]
👍

**Comment by yzl** [comment]
👍

**Comment by jaymalasinha** [comment]
👍

**Pull request merged**
